export default {
    BACKGROUND_COLOR: 'gray',
    PRIMARY_TEXT_CCOLOR: 'black',
    TEXT_COLOR_INVERT: '#fff',
    PRIMARY_COLOR: '#2ABB9B',
    SECONDARY_COLOR: '#264348',
    GALLERY_COLOR: '#87D37C',
    YELLOW_COLOR: '#99C13A',
    DIVIDER_COLOR: '#757D75',
}