export default {
    BACKGROUND_COLOR: 'gray',
    PRIMARY_TEXT_CCOLOR: 'black',
    TEXT_COLOR_INVERT: '#fff',
    PRIMARY_COLOR: '#875F9A',
    SECONDARY_COLOR: '#5D3F6A',
    GALLERY_COLOR: '#EEEEEE',
    YELLOW_COLOR: '#F3C13A',
    DIVIDER_COLOR: '#757D75',
}